openapi: '3.0.0'
info:
    version: 1.0.0
    title: Exchange rate API
    description: Microservice for retrieving exchange rates information

paths:
    /rates:
        get:
            description: Get exchange rates
            responses:
                '200':
                    description: Object containing exchange rates information
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/ExchangeRates'

components:
    securitySchemes:
        BasicAuth:
          type: http
          scheme: basic
    schemas:
        ExchangeRates:
            description: Exchange rates for multiple currencies for a single base currency
            type: object
            properties:
                base:
                    description: The base currency
                    type: string
                currencies:
                    type: array
                    items:
                        $ref: '#/components/schemas/CurrencyExchangeRate'

        CurrencyExchangeRate:
            description: Exchange rates for a single currency on multiple dates
            type: object
            properties:
                currency_code:
                    description: Currency code for the exchange rates
                    type: string
                rates:
                    type: array
                    items:
                        $ref: '#/components/schemas/ExchangeRate'

        ExchangeRate:
            description: Exchange rate on a given date
            type: object
            properties:
                date:
                    description: Date of exchange rate yyyy-mm-dd
                    type: string
                rate:
                    description: Exchange rate on given date i.e. 0.80213
                    type: number
                    format: float
