openapi: '3.0.0'
info:
    version: 1.0.0
    title: Exchange rate API
    description: Client spec to get apirates from api.ratesapi.io

paths:
    /api/{date}:
        get:
            description: Get rates for base currency, single date and comma list of currencies. i.e. https://api.ratesapi.io/api/2020-01-12?base=EUR&symbols=GBP,HKD,USD
            parameters:
                -   in: path
                    name: date
                    description: The date of the requested exchange rates
                    schema:
                        type: string
                        format: date
                    required: true

                -   in: query
                    name: symbols
                    description: Comma seperated list of currency codes for the requested exchange rates i.e. GBP,HKD,USD
                    schema:
                        type: string
                    required: false
                    allowReserved: true

            responses:
                '200':
                    description: Object containing exchange rates information
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ClientExchangeRates'

components:
    schemas:
        ClientExchangeRates:
            description: Exchange rates for a single currency on multiple dates
            type: object
            properties:
                base:
                    description: The base currency i.e. EUR
                    type: string
                rates:
                      $ref: '#/components/schemas/ClientCurrencyRates'
                date:
                    description: Date of exchange rate yyyy-mm-dd
                    type: string

        ClientCurrencyRates:
            description: Exchange rate on a given date
            type: object
            additionalProperties:
                type: string
